env:
  global:
    secure: FNZoZ7N5uRNzXzi3TXDLjbQi1bKmbuL8iPJin2y6+FRJCVchFhGLbCKfgIqOzlP1Qwa/2Zqoy55cxwr/Qu1WSBfksjOkrSyyKbguxRbibjsraP0U4vVTmf++y4CTSOGNlveWTNZObd3F4Tax3SwRjs4l7byuILrM4XIX36RvipqLMNbU7SKH7dlycxTjosKD40JduJDkCHd6M/9EAAclQJhc2erB2A48YH17YOcDZH51e80NKakSDccY2xDkz7j5mRSenCrZhNaOWkkitveLOM24LwMhjoEYr4q62DbVZscLOxbv6x2pjkMxhXZbBoGvcAX0mH9HPCgwLMYmW4Jrn9H+4Tk5hhFnV1JwQ4VwmInrHLhuPwW2q1+r8QgKKiJGKv//07cAlRgVBeuubhac86F1QXnvCszwxym1TlaMmcJ0IUYBvyfepQUyAXVC709J/vMG5yKfnmFIImdajYuPznY8MqPxI6idIgkYeRNgnysJdQ0g6uiQFRm/Kl9xbZ/PqR9k2O9KFbDPMRe84TDHCabu5C+7kko2BDls/WfxOfc88F01iGGLEUCOWtGi6A4jjcJKhudgL3MRnxJeU/pLQjR+kICw5iWJl7JRmPACedzn5FiSeoYzy+9RQDnK0kbMLaw4T/tTiMHr86syDwx+Tis0EnhACo5H/IjYCwg1iAc=
before_deploy:
- openssl aes-256-cbc -K $encrypted_8382f1c42598_key -iv $encrypted_8382f1c42598_iv
  -in .travis/keys.tar.enc -out .travis/keys.tar -d
- tar xvf .travis/keys.tar
